name: 'Check mentions'
description: 'Check mentions in issues and pull requests for misspellings by inferring from access to the repository.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: at-sign
  color: gray-dark
